# action.yml
name: 'Approved PR'
description: 'Check if GitHub pull request is approved'
inputs:
  github_token:
    description: 'Repo token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
